### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by XXIrene** [anotheren/TrafficPolice#2]
Hi, I‘m new for swift 
I wonder after define the func like you showed in readme like this
func post(summary: TrafficSummary) {
        print("this is traffic:\(summary)")
        
    }
How can I use the post function in my button which means that when I use it what should I put for the summary

Looking for your response

**Comment by anotheren** [comment]
Have you check Requirements ? (iOS 8.0+ Xcode 9+ Swift 4.0+)
Have you ever set the `TrafficManager.shared.delegate` as yourself ?

**Comment by XXIrene** [comment]
设置了呀就是在调用post的时候我不知道summary：后面的参数应该写什么？

**Comment by anotheren** [comment]
你应该检查一下函数的签名，然后去看类型的签名，全部源码都在那里，全部都是结构化的数据了，要啥拿啥就好了
```swift
public struct TrafficSummary {
    public let wifi: TrafficStatus
    public let wwan: TrafficStatus
}

public struct TrafficStatus {
    public let speed: TrafficSpeed
    public let data: TrafficData
}
```

**Comment by XXIrene** [comment]
解决啦！非常感谢！大佬写的这个太好用了！
