### ISSUE TITLE
Can this lib monitor only traffic usage for the app where it is used ?

### ISSUE THREAD

**Issue by yarodevuci** [anotheren/TrafficPolice#3]
I only see overall traffic for device
I need only network data traffic usage for the app where this library is used. Can I get that data?

**Comment by anotheren** [comment]
Sorry, you can't. If you only need your app's traffic usage, you'd better write your own socket manager,and then send/receive/summary 😂

**Comment by yarodevuci** [comment]
@anotheren I see, I did not know that
Thank you!
